# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LETSPARTY' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LETSPARTY
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
  target 'LETSPARTYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LETSPARTYUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
